baseURL = 'http://192.168.1.3:8000/'
languageCode = 'en-us'
title = 'Notebook'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
